### ISSUE TITLE
page.js support for hybrid apps (e.g. phonegap native apps)

### ISSUE THREAD

**Issue by kdonald** [visionmedia/page.js#18]
I experimented with adding page.js to the little test app here: https://github.com/kdonald/graceworks. It works fine when served to a HTML 5 browser such as Chrome (using something like serve running on localhost:3000, for example). However, the app doesn't work when wrapped in a Apache Cordova (phonegap) project and targeted at the iPhone simulator or an iPhone device. Specifically, it looks like the default ("/") route is never firing so no content ever gets rendered for the user to interact with.

I've found very little docs on the web about IOS's/Phonegap's support for the HTML5 history API. Previously, I was using path.js for navigation with #/fragments and it was working for the most part; however, window.history.back() did not work consistently in a native Phonegap environment and that's why I wanted to try out page.js (specifically, users were unable to navigate back to the #/home or root page of the app ("default route"), while window.history.back did work as expected when navigating from a child page to a parent that was not the root).

What are your thoughts for supporting multi-page hybrid (phonegap) apps? jQuery Mobile appears to maintain its own url history stack and does not rely on HTML 5 by default. I'm intentionally not using JQuery Mobile's navigation support in my app though as I wanted more control (I've built my own page navigator/router abstraction on-top of page js that routes URLs to MVC objects that handle page interactions... would love to see page.js just working when running on a native HTML container like in a Phonegap environment).

**Comment by mickharper** [comment]
Just wanted to give a quick 2019 update for anyone using Page.js with Cordova (on iOS) that's stepping through the old comments here. If you use one of the newer WKWebView plugins (like [Ionic's](https://github.com/ionic-team/cordova-plugin-ionic-webview)), you don't need to do anything special. It should work out of the box since it abstracts away the file protocol without needing to set hashbang, dispatch, click, etc.

This setup also allows you to use dynamic imports so you can lazily load your templates. So far I've found really responsive and it boots very quickly. Thanks page.js team!
