### ISSUE TITLE
page.exit blocks a page dispatching

### ISSUE THREAD

**Issue by A** [visionmedia/page.js#193]
Page'll dispatch `topics/` only when `next()` is called in `page.exit()`:

``` js
page('/topics/:id/', function () {
  console.log('topic');
});

page.exit('/topics/:id', function() {
  topicPage.remove();
});

page('/topics/', function () {
  // never dispatched
});

page();
page('/topics/1');
setTimeout(function () { page('/topics/') }, 0); // 
```

This behaviour is confused and its not seems like ordinary `page.show()` middlewares.  I think, the problem [is here](https://github.com/visionmedia/page.js/blob/master/index.js#L245). ping @hughsk

**Comment by gertsonderby** [comment]
At the same time, I'm having the problem that I want the ability to block on an exit route, but it seems to work inconsistently - specifically it pushes the history state even if next is not called. Related? Different issue?

**Comment by gertsonderby** [comment]
Should we do this for exit routes only I'm unsure of how Express deals with non-next'ing middlewares, does it do similar things to what's described in here?

**Comment by axelpale** [comment]
IMHO it is logical that `next` needs to be called. I am using Express a lot, so I expect the execution of middleware chain to stop if I do not call `next()`.

**However** the documentation should put emphasis on the importance of calling `next()`. Currently there is no mention what happens if `next` is omitted. The position of `exit` in the middleware chain is not trivial and that caused me, and multiple others I believe, to spend tens of minutes wondering where is the problem.
