### ISSUE TITLE
How do you make the 'hash' example work when { hashbang: true }?

### ISSUE THREAD

**Issue by alainjacomet** [visionmedia/page.js#231]
The question says it all. I'm trying to make the example under `examples/hash/` work the same way it does, only using the `{ hashbang: true }` option, but no avail. 

I've also tried setting `<base href="/hash/">`, but that seems to get into an infinite redirection. After that, removing `page.base('/hash')` seems to do the trick, but then the location bar displays `http://localhost:4000/hash/#!/hash/` and the `#` and `#subsection` links stop working properly. 

How can I do this ?
Thanks

**Comment by TitanKing** [comment]
The #! is very dodge, for example if you type in the addressbar the following http://somesite.com/test#!/some-route it will work, but if you do http://somesite.com/test/#!/some-route (slash after test) it will not find the route.

So in your URLS do not have a slash after before the #!, I do not know if this will get fixed, I can probably look at it too.

**Comment by TitanKing** [comment]
Ok just to follow up, do not rely on build in { hashbang: true } rather make page.base('/#!'), this seems to solve all issues so far.

**Comment by dbismut** [comment]
Thanks @TitanKing this sure helped!

**Comment by denevell** [comment]
Not sure if this affects you, but when I disable {hashbang: true} and set page.base("/#!") and have a url like localhost/~myuser/somepath/ then when I load the url, I get http://localhost/#!/~myuser/somepath/ which obviously fails on reload. Without the leading slash in the base, I get http://localhost/~myuser/somepath/#!/~myuser/somepath/

I'm having some real problems with #!, which is a pity because it's the best feature for me in page.js. I'll try to submit some CRs.

**Comment by raine** [comment]
> Ok just to follow up, do not rely on build in { hashbang: true } rather make page.base('/#!'), this seems to solve all issues so far.

This is really weird behavior.

**Comment by ooscarr** [comment]
I added
```javascript
page('/~myuser/somepath/', function () {
  app.route = 'home';
});
```
to my [polymer routing.html](https://github.com/PolymerElements/polymer-starter-kit/blob/v1.0.2/app/elements/routing.html) file, it's ugly but at least it loads, using `{ hashbang: true }`

**Comment by wenerme** [comment]
I meet the same problem, this is how I solve, awkward but works

```
page('/weapon/add', (ctx)=> {
      this.addWeapon();
    });
    page('/weapon/:id', (ctx)=> {
      this.showWeapon(ctx.params.id);
    });
    page('/weapon/:id/edit', (ctx)=> {
      this.editWeapon(ctx.params.id);
    });
    page('weapon/add', (ctx)=> {
      this.addWeapon();
    });
    page('weapon/:id', (ctx)=> {
      this.showWeapon(ctx.params.id);
    });
    page('weapon/:id/edit', (ctx)=> {
      this.editWeapon(ctx.params.id);
    });
```

After this, use `http://localhost:5000/#!weapon/2/edit` instead `http://localhost:5000/#!/weapon/2/edit`.

Will pagejs attempt to fix this ?

**Comment by matthewp** [comment]
Hey everyone! This sounds like the same bug as https://github.com/visionmedia/page.js/issues/242 which was fixed by https://github.com/visionmedia/page.js/pull/447.

Try out 1.8.0 and let me know if you still see this problem. I'm going to assume this is fixed and close the issue, but will reopen if you tell me otherwise. Thanks!
