### ISSUE TITLE
Cannot GET /some_url

### ISSUE THREAD

**Issue by pokaxperia** [visionmedia/page.js#327]
Hello, I use page.js with gulp, browserify and watchify. I run a server with localhost: xxxx and when I make any changes in my code, the browser reloads to reflect changes, but the same url gives me a legend "Cannot GET /some page". 

Example: 
//domain.com/some_url = > it show page normally..
When browser reloads to reflect changes:
//domain.com/some_url = > Cannot GET /some_url

Or even when simply I reload the browser with f5 or cmd + r = Cannot GET /some_url

How can resolve this?

**Comment by woodlandhunter** [comment]
It sounds like you're only handling the route client side. The back-end server must be set up to somehow handle the request sent to /some_url as well.

**Comment by jbwebesign** [comment]
@pokaxperia did you have any luck with this? Really want to use this page.js for a personal project but these similar issues are causing me grief, I have a similar local development setup with Gulp/Browserify.

**Comment by woodlandhunter** [comment]
It is very likely the *back-end* server was not set up to handle the route in @pokaxperia's case. You need to handle /some_url on the client and server.

Example:

You browse to `/` and the client side js is loaded, page.js routes are set up. You click on a link: `/some_url`. page.js intercepts the click and page.js runs your handler (no http request is made). The url in the address bar is now `/some_url`.

Now, you hit f5 to reload... the web browser makes a new http request to `/some_url`, which 404s, because your back-end is only serving `/`...


@jbwebesign  If this isn't what is happening to you, please open a new issue describing the issue in detail.

**Comment by jbwebesign** [comment]
Hey thanks very much for the explanation. I did some reading through browsersync docs and found the configuration entries I needed to sort this out in my local environment.

**Comment by matthewp** [comment]
Sounds like this one was worked out! Great!
