### ISSUE TITLE
Suggestion: deprecate and suggest alternatives

### ISSUE THREAD

**Issue by rstacruz** [visionmedia/page.js#346]
[riot-route](https://www.npmjs.com/package/riot-route) has a very similar API to page.js and is more robust—it supports hash changes as well as pushState.

**Comment by rstacruz** [comment]
bump. @A?

**Comment by barry-johnson** [comment]
Not sure how "very similar" the API is (and I like Riot just fine). Riot's Route has no named parameters, just (*), no multiple handlers or middleware, no concept of "next()" within handlers (which is pointless, since no multiple handlers), all of which make it completely inconsistent with Express' interface, which is the point of this library.

On the other hand, if the 1% of global users on IE<10 are important to you...

**Comment by matthewp** [comment]
Not planning on depreciating page.js 😎
