### ISSUE TITLE
Is this router isomorphic? 

### ISSUE THREAD

**Issue by PaulMaly** [visionmedia/page.js#362]
Can I use Page.JS on both sides: browser & NodeJS ?

**Comment by kethinov** [comment]
Not by default, but I wrote a plugin that enables you to remap the page.js API to the Express API: https://github.com/kethinov/page.js-express-mapper.js

**Comment by rstacruz** [comment]
Hi @PaulMaly, consider using http://riotjs.com/api/route/ instead which has support for isomorphic usage.

**Comment by Shyam-Chen** [comment]
https://github.com/kriasoft/universal-router

**Comment by PaulMaly** [comment]
@Shyam-Chen I check this router and it seems, that it capture nothing. It's just impose the route you already know to predefined routes table. It's not working with HTML5 History API and even server http requests.

**Comment by lapinskicho** [comment]
@PaulMaly universal-router works as it advertises.  It uses path-to-regexp as the route matching engine, so for instance if you use Express at your back-end, you can share your route table for both the front-end and back-end, which is a big plus over many other routing solutions.  A router should not know anything about browser history, due to separation of concerns, but universal-router certainly works with HTML5 History API, you just need to plug that component to your app appropriately.

**Comment by matthewp** [comment]
Yep, as answered, page.js is only for the frontend.
