### ISSUE TITLE
CommonJS "require()"  in page.js file loaded from browser

### ISSUE THREAD

**Issue by wollanup** [visionmedia/page.js#521]
Just to make sure...
Is that an expected behavior that page.js uses 
```javascript
var pathtoRegexp = require('path-to-regexp');
```
in the latest commit ?

The file page.js is supposed to be used in a client side environment (browser), not in Node environment ?

**Comment by bbarr** [comment]
_TLDR - Use the cdnjs or unpkg links on the README, not the rawgit link on the public marketing site. Keep the version at 1.11.1_

This is not ES6, this is commonjs and certainly has no place in the built file of a client-side library. The tests don't catch it either, so, must be configured incorrectly or else it is going through another build stage for them.. which would make even less sense. Hopefully someone with time (unfortunately not I) can dig into it more today, because this is probably affecting a lot of people.

**Comment by wollanup** [comment]
@bbarr 
Yes I switched to 
https://unpkg.com/page@1.11.1/page.js 
instead of
https://cdn.rawgit.com/visionmedia/page.js/master/page.js
(and told my devs again to never use untagged/master versions! :angry: )

**Comment by hed101** [comment]
...just before the weekend :/
Had to switch from the master-version as well. grrrrmpfff

**Comment by matthewp** [comment]
Not sure why this happened. Looking into it.

**Comment by matthewp** [comment]
Ok, this is fixed in 1.11.2. Sorry about that.

**Comment by hed101** [comment]
Thanks.
